# 服务端口号
server:
  port: 8090

# 服务名称
spring:
  application:
    name: spring-cloud-nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          key1 : aaa
          key2 : bbb