# 服务端口号
server:
  port: ${random.int[10000,19999]}  # 服务器端口。默认为 8080

# 服务名称
spring:
  application:
    name: netflix-ribbon-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
