# 服务端口号
server:
  port: 8080

# 服务名称
spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

      routes:
        - id: header-rd
          uri: http://localhost:8888/header
          filters:
            - AddRequestHeader=header, addHeader
            - AddRequestParameter=param, addParam
          predicates:
            - Path=/hehe

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # Eureka-Server 地址


logging:
  level:
    org.springframework.cloud.gateway: debug