# 服务端口号
server:
  port: 8090

# 服务名称
spring:
  application:
    name: spring-cloud-eureka-discovery-consumer

eureka:
  client:
    register-with-eureka: true # 注册到 Eureka-Server，默认为 true
    fetch-registry: true # 从 Eureka-Server 获取注册表，默认为 true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # Eureka-Server 地址